server.port=8080
document360.api.key=TvrDSpEEHxJVgfim9Gbqpw9ZZ5Vz2XwCFnPFqQ2DMFBl/A+ZI4PAfRO9qOGyG14nflFJ5n/8HuMsM2wiNzlBmT0QTuT1ktlNh0ueEqCKaRaSwygmVAbl3u5oKyyt3IYcKTLXz8XbxfYcXyG36rCFvA==
document360.api.base-url=https://apihub.document360.io/v2
document360.project.version-id=8de99e99-94af-4315-9047-8fd5f90b2f8d
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
document360.user-id=9bc90a13-4c7a-45e6-b51d-839bc3a5a209
document360.category-id=8a826fb1-771e-4f8f-a3f5-88ba63907422
